# Simple Makefile for mySAT
# Equivalent to: g++ mySAT.cpp parser.cpp -o mySAT
# THIS FILE WAS GENERATED BY THE AI TOOL CLAUDE!!!

CXX      = g++
CXXFLAGS = -std=c++17 -O2 -Wall
TARGET   = mySAT
SOURCES  = mySAT.cpp parser.cpp
 
# Default target: build mySAT
all: $(TARGET)
 
$(TARGET): $(SOURCES)
	$(CXX) $(CXXFLAGS) $(SOURCES) -o $(TARGET)
 
# Remove the built executable
clean:
	rm -f $(TARGET)
 
.PHONY: all clean