/* -----------------------------------------------------------------------
 * parser.h
 * --------
 * DIMACS CNF parser.
 * Reads a CNF formula in DIMACS format and populates a Formula struct
 * that the DPLL solver consumes.
 *
 * DIMACS CNF format:
 *   c  comment line  (ignored)
 *   p cnf <num_vars> <num_clauses>
 *   <lit> <lit> ... 0    (one or more literals per line; 0 ends a clause)
 *
 *   Literals: positive integer  = positive literal for that variable
 *             negative integer  = negative literal for that variable
 *   Variables are numbered 1 .. num_vars.
 * 
 * --------
 * THIS FILE WAS GENERATED BY THE AI TOOL CLAUDE!!!
 * THIS FILE IS INFRASCTUCTURE CODE TO SIMPLY PARSE THE CNF BENCHMARK
 * ----------------------------------------------------------------------- */

#pragma once

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

/* -----------------------------------------------------------------------
 * Formula
 *
 * Plain data structure produced by the parser.
 * Variables are 1-based; literals are signed integers (+/-var).
 * ----------------------------------------------------------------------- */
struct Formula {
    int num_vars    = 0;   /* number of variables                         */
    int num_clauses = 0;   /* declared clause count (informational only)  */
    std::vector<std::vector<int>> clauses;  /* each clause: list of lits  */
};

/* -----------------------------------------------------------------------
 * parse_dimacs  (file path)
 *
 * Opens `path`, parses it as DIMACS CNF, fills `formula`.
 * Returns true on success; prints to stderr and returns false on error.
 * ----------------------------------------------------------------------- */
bool parse_dimacs(const std::string& path, Formula& formula);

/* -----------------------------------------------------------------------
 * parse_dimacs  (stream overload – handy for unit-testing)
 * ----------------------------------------------------------------------- */
bool parse_dimacs(std::istream& in, Formula& formula);
