/* -----------------------------------------------------------------------
 * parser.cpp
 * ----------
 * Implementation of the DIMACS CNF parser declared in parser.h.
 * ----------
 * THIS FILE WAS GENERATED BY THE AI TOOL CLAUDE
 * THIS FILE IS INFRASCTUCTURE CODE TO SIMPLY PARSE THE CNF BENCHMARK
 * ----------------------------------------------------------------------- */

#include "parser.h"

/* -----------------------------------------------------------------------
 * parse_dimacs  (stream)
 * ----------------------------------------------------------------------- */
bool parse_dimacs(std::istream& in, Formula& formula) {

    formula = Formula{};            /* reset output */

    bool header_seen = false;
    std::vector<int> pending;       /* literals for the clause being built  */

    /* Helper: commit whatever is in `pending` as a new clause. */
    auto flush_clause = [&]() {
        if (pending.empty()) return;
        formula.clauses.push_back(pending);
        pending.clear();
    };

    std::string line;
    while (std::getline(in, line)) {

        /* strip Windows-style CR */
        if (!line.empty() && line.back() == '\r')
            line.pop_back();

        if (line.empty()) continue;

        const char first = line[0];

        /* ---- comment -------------------------------------------------- */
        if (first == 'c' || first == 'C')
            continue;

        /* ---- end-of-file marker used by some generators --------------- */
        if (first == '%')
            break;

        /* ---- problem line --------------------------------------------- */
        if (first == 'p') {
            std::istringstream ss(line);
            std::string p_tok, fmt_tok; 

            if (!(ss >> p_tok >> fmt_tok
                     >> formula.num_vars >> formula.num_clauses)) {
                std::cerr << "parser error: malformed problem line:\n  "
                          << line << "\n";
                return false;
            }
            if (fmt_tok != "cnf") {
                std::cerr << "parser error: expected 'p cnf ...', got '"
                          << fmt_tok << "'\n";
                return false;
            }
            if (formula.num_vars <= 0 || formula.num_clauses < 0) {
                std::cerr << "parser error: invalid variable/clause counts\n";
                return false;
            }
            /* create the vector containing all the clauses */
            formula.clauses.reserve(
                static_cast<std::size_t>(formula.num_clauses));
            header_seen = true;
            continue;
        }

        /* ---- clause data (only meaningful after the header) ----------- */
        if (!header_seen)
            continue;

        std::istringstream ss(line);
        int lit;
        while (ss >> lit) {
            if (lit == 0) {
                /* 0 terminates the current clause, 0 is a non valid literal*/
                flush_clause();
            } else {
                int var = (lit > 0) ? lit : -lit;
                /* if a clause has more literals than mentioned in the header */
                if (var > formula.num_vars) {
                    std::cerr << "parser error: literal " << lit
                              << " references variable " << var
                              << " which exceeds declared num_vars="
                              << formula.num_vars << "\n";
                    return false;
                }
                pending.push_back(lit);
            }
        }
        /* Note: if a clause spans multiple lines the pending buffer just
         * keeps accumulating until we encounter a 0 on a later line.     */
    }

    /* Flush any clause not terminated by 0 (lenient parsing). */
    flush_clause();

    if (!header_seen) {
        std::cerr << "parser error: no 'p cnf' header found\n";
        return false;
    }

    return true;
}

/* -----------------------------------------------------------------------
 * parse_dimacs  (file path)
 * ----------------------------------------------------------------------- */
bool parse_dimacs(const std::string& path, Formula& formula) {
    std::ifstream in(path);

    /* Verify if the file can be opened */
    if (!in.is_open()) {
        std::cerr << "parser error: cannot open '" << path << "'\n";
        return false;
    }
    return parse_dimacs(in, formula);
}
