#!/bin/bash
#
# test_runner.sh — Run ./mySAT against every .cnf file in ./benchmarks
#                  and write a single elapsed-time summary file.
#
# Each benchmark is run with a hard timeout (default 10 minutes). If a
# benchmark exceeds the timeout it is killed, recorded as TIMEOUT in the
# summary, and the runner moves on to the next benchmark.
#
# Usage:
#   ./test_runner.sh                  # run all benchmarks (10 min timeout each)
#   ./test_runner.sh -t 300           # set a 300-second timeout per benchmark
#   ./test_runner.sh -t 0             # disable the per-benchmark timeout
#   ./test_runner.sh -d path/to/dir   # use a different benchmark directory
#   ./test_runner.sh -o summary.txt   # write summary to a custom path
#
# THIS FILE WAS GENERATED BY THE AI TOOL CLAUDE!!!
# THIS FILE IS INFRASTRUCTURE CODE TO SIMPLY TEST MULTIPLE BENCHMARKS AGAINST THE SOLVER.

set -u

# -------- Defaults --------
SOLVER="./mySAT"
BENCH_DIR="./benchmarks"
TIMEOUT_SECS=600        # default: 10 minutes per benchmark (0 = no timeout)
LOG_ROOT="./benchmark_logs"
SUMMARY_FILE=""         # default: <LOG_ROOT>/benchmark_times_<timestamp>.txt
PER_DIR_LIMIT=10        # take this many .cnf files from each directory

# -------- Parse args --------
while getopts "d:t:s:l:o:n:h" opt; do
    case "$opt" in
        d) BENCH_DIR="$OPTARG" ;;
        t) TIMEOUT_SECS="$OPTARG" ;;
        s) SOLVER="$OPTARG" ;;
        l) LOG_ROOT="$OPTARG" ;;
        o) SUMMARY_FILE="$OPTARG" ;;
        n) PER_DIR_LIMIT="$OPTARG" ;;
        h)
            echo "Usage: $0 [-d benchmark_dir] [-t timeout_secs] [-s solver] [-l log_root] [-o summary_file] [-n per_dir_limit]"
            echo "       Default timeout is 600 seconds (10 minutes). Use -t 0 to disable."
            exit 0
            ;;
        *) echo "Invalid option. Use -h for help." >&2; exit 1 ;;
    esac
done

# -------- Sanity checks --------
if [[ ! -x "$SOLVER" ]]; then
    echo "Error: solver '$SOLVER' not found or not executable." >&2
    exit 1
fi

if [[ ! -d "$BENCH_DIR" ]]; then
    echo "Error: benchmark directory '$BENCH_DIR' does not exist." >&2
    exit 1
fi

# --------------------------------------------------------------------
# SAFETY: this script must NOT modify anything inside $BENCH_DIR.
# The only filesystem changes it ever makes are:
#   1. create the log root directory ($LOG_ROOT)
#   2. write the summary text file ($SUMMARY_FILE)
# Refuse to run if either of those would land inside the benchmark
# directory (e.g. if someone passes -o benchmarks/foo.txt by mistake).
# --------------------------------------------------------------------
abs_bench=$(cd "$BENCH_DIR" && pwd -P)

is_inside_bench() {
    local target_parent
    target_parent=$(cd "$(dirname "$1")" 2>/dev/null && pwd -P) || return 1
    [[ "$target_parent" == "$abs_bench" || "$target_parent" == "$abs_bench"/* ]]
}

# Default summary filename uses a timestamp so repeated runs don't overwrite,
# and lives inside the benchmark log directory.
TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
if [[ -z "$SUMMARY_FILE" ]]; then
    if is_inside_bench "$LOG_ROOT/."; then
        echo "Error: log root '$LOG_ROOT' is inside the benchmark directory. Refusing to run." >&2
        exit 1
    fi
    mkdir -p "$LOG_ROOT"
    SUMMARY_FILE="$LOG_ROOT/benchmark_times_${TIMESTAMP}.txt"
else
    if is_inside_bench "$SUMMARY_FILE"; then
        echo "Error: summary file '$SUMMARY_FILE' is inside the benchmark directory. Refusing to run." >&2
        exit 1
    fi
    # Make sure the parent of an explicit -o path exists too
    mkdir -p "$(dirname "$SUMMARY_FILE")"
fi

# Find every directory under BENCH_DIR that directly contains .cnf files,
# then take the first PER_DIR_LIMIT .cnf files from each such directory.
# -print0 / read -d '' is used so paths with spaces or newlines work correctly.
dirs=()
while IFS= read -r -d '' d; do
    dirs+=("$d")
done < <(find "$BENCH_DIR" -type f -name '*.cnf' -printf '%h\0' | sort -zu)

if (( ${#dirs[@]} == 0 )); then
    echo "No .cnf files found in $BENCH_DIR"
    exit 0
fi

benchmarks=()
for dir in "${dirs[@]}"; do
    count=0
    while IFS= read -r -d '' f; do
        benchmarks+=("$f")
        count=$((count + 1))
        if (( PER_DIR_LIMIT > 0 && count >= PER_DIR_LIMIT )); then
            break
        fi
    done < <(find "$dir" -maxdepth 1 -type f -name '*.cnf' -print0 | sort -z)
done

total=${#benchmarks[@]}
index=0
total_time=0
sat_count=0
unsat_count=0
unknown_count=0
timeout_count=0
fail_count=0

# Pretty timeout label for the summary header
if (( TIMEOUT_SECS > 0 )); then
    timeout_label="${TIMEOUT_SECS}s"
else
    timeout_label="disabled"
fi

# -------- Header --------
printf "Running %d benchmark(s) with %s\n" "$total" "$SOLVER"
printf "Per-benchmark timeout: %s\n" "$timeout_label"
printf "Summary will be written to %s\n\n" "$SUMMARY_FILE"

{
    echo "SAT Solver Benchmark Times"
    echo "=========================="
    echo "Run started: $(date)"
    echo "Solver:      $SOLVER"
    echo "Benchmarks:  $BENCH_DIR"
    echo "Timeout:     $timeout_label"
    echo "Per-dir cap: ${PER_DIR_LIMIT} (0 = no cap)"
    echo "Directories: ${#dirs[@]}"
    echo
    printf "%-70s %-10s %-10s %-12s\n" "BENCHMARK" "RESULT" "VERDICT" "TIME(s)"
    printf "%-70s %-10s %-10s %-12s\n" "----------------------------------------------------------------------" "----------" "----------" "------------"
} > "$SUMMARY_FILE"

# Temp file for capturing solver stdout so we can scan it for SAT/UNSAT.
SOLVER_OUT=$(mktemp)
trap 'rm -f "$SOLVER_OUT"' EXIT

# -------- Run each benchmark --------
# NOTE: this loop never exits early. Even if a benchmark times out, fails,
# or returns garbage, we record the result and continue to the next file
# until every benchmark has been attempted.
for bench in "${benchmarks[@]}"; do
    index=$((index + 1))
    # Use the path relative to the benchmark dir so nested files stay
    # distinguishable in the summary (e.g. "uf50/uf50-01.cnf").
    name="${bench#$BENCH_DIR/}"

    printf "[%d/%d] %s ... " "$index" "$total" "$name"

    # Truncate the temp file from the previous run before reusing it
    : > "$SOLVER_OUT"

    start=$(date +%s.%N)
    if (( TIMEOUT_SECS > 0 )); then
        # --foreground keeps signals working as expected; --kill-after sends
        # SIGKILL 5s after SIGTERM so misbehaving solvers can't ignore the
        # timeout and stall the entire run.
        timeout --foreground --kill-after=5s "${TIMEOUT_SECS}s" \
            "$SOLVER" "$bench" > "$SOLVER_OUT" 2>&1
        status=$?
    else
        "$SOLVER" "$bench" > "$SOLVER_OUT" 2>&1
        status=$?
    fi
    end=$(date +%s.%N)

    elapsed=$(awk -v s="$start" -v e="$end" 'BEGIN { printf "%.3f", e - s }')
    total_time=$(awk -v t="$total_time" -v e="$elapsed" 'BEGIN { printf "%.3f", t + e }')

    # `timeout` returns 124 on timeout, 137 if it had to escalate to SIGKILL.
    if (( status == 124 || status == 137 )); then
        result="TIMEOUT"
        verdict="TIMEOUT"
        timeout_count=$((timeout_count + 1))
    elif (( status == 0 )); then
        result="OK"
        # Determine SAT / UNSAT from solver stdout.
        # Check UNSAT first since "SAT" is a substring of "UNSAT".
        if grep -qiwE 'unsat|unsatisfiable' "$SOLVER_OUT"; then
            verdict="UNSAT"
            unsat_count=$((unsat_count + 1))
        elif grep -qiwE 'sat|satisfiable' "$SOLVER_OUT"; then
            verdict="SAT"
            sat_count=$((sat_count + 1))
        else
            verdict="?"
            unknown_count=$((unknown_count + 1))
        fi
    else
        result="FAIL($status)"
        verdict="-"
        fail_count=$((fail_count + 1))
    fi

    printf "%s %s (%ss)\n" "$result" "$verdict" "$elapsed"
    printf "%-70s %-10s %-10s %-12s\n" "$name" "$result" "$verdict" "$elapsed" >> "$SUMMARY_FILE"
done

# -------- Footer --------
{
    echo
    echo "------------------------------------------"
    printf "Total benchmarks: %d\n" "$total"
    printf "SAT:              %d\n" "$sat_count"
    printf "UNSAT:            %d\n" "$unsat_count"
    printf "Timeouts:         %d\n" "$timeout_count"
    printf "Failures:         %d\n" "$fail_count"
    printf "Unknown:          %d\n" "$unknown_count"
    printf "Total time:       %s seconds\n" "$total_time"
    echo "Run finished:     $(date)"
} >> "$SUMMARY_FILE"

echo
echo "Summary written to: $SUMMARY_FILE"